/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as MasterRouteImport } from './routes/master'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterPlanosRouteImport } from './routes/master.planos'
import { Route as MasterPainelRouteImport } from './routes/master.painel'
import { Route as MasterNovaBarbeariaRouteImport } from './routes/master.novaBarbearia'
import { Route as MasterListaBarbeariasRouteImport } from './routes/master.listaBarbearias'
import { Route as MasterConfiguracoesRouteImport } from './routes/master.configuracoes'
import { Route as MasterAssinaturasRouteImport } from './routes/master.assinaturas'
import { Route as DemoServicosRouteImport } from './routes/demo.servicos'
import { Route as DemoRelatoriosRouteImport } from './routes/demo.relatorios'
import { Route as DemoProfissionaisRouteImport } from './routes/demo.profissionais'
import { Route as DemoFinanceiroRouteImport } from './routes/demo.financeiro'
import { Route as DemoEquipeRouteImport } from './routes/demo.equipe'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as DemoConfiguracoesRouteImport } from './routes/demo.configuracoes'
import { Route as DemoClientesRouteImport } from './routes/demo.clientes'
import { Route as DemoAigrowthRouteImport } from './routes/demo.aigrowth'
import { Route as DemoAgendaRouteImport } from './routes/demo.agenda'
import { Route as ConfirmarTokenRouteImport } from './routes/confirmar.$token'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProfissionaisRouteImport } from './routes/app.profissionais'
import { Route as AppProdutosRouteImport } from './routes/app.produtos'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLembretesRouteImport } from './routes/app.lembretes'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComandasRouteImport } from './routes/app.comandas'
import { Route as AppClubeRouteImport } from './routes/app.clube'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppAigrowthRouteImport } from './routes/app.aigrowth'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing/webhook'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPlanosRoute = MasterPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPainelRoute = MasterPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => MasterRoute,
} as any)
const MasterNovaBarbeariaRoute = MasterNovaBarbeariaRouteImport.update({
  id: '/novaBarbearia',
  path: '/novaBarbearia',
  getParentRoute: () => MasterRoute,
} as any)
const MasterListaBarbeariasRoute = MasterListaBarbeariasRouteImport.update({
  id: '/listaBarbearias',
  path: '/listaBarbearias',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => MasterRoute,
} as any)
const DemoServicosRoute = DemoServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRelatoriosRoute = DemoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProfissionaisRoute = DemoProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinanceiroRoute = DemoFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEquipeRoute = DemoEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConfiguracoesRoute = DemoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientesRoute = DemoClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAigrowthRoute = DemoAigrowthRouteImport.update({
  id: '/aigrowth',
  path: '/aigrowth',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DemoRoute,
} as any)
const ConfirmarTokenRoute = ConfirmarTokenRouteImport.update({
  id: '/confirmar/$token',
  path: '/confirmar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProfissionaisRoute = AppProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLembretesRoute = AppLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComandasRoute = AppComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => AppRoute,
} as any)
const AppClubeRoute = AppClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppAigrowthRoute = AppAigrowthRouteImport.update({
  id: '/aigrowth',
  path: '/aigrowth',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/agendar/$slug',
  path: '/agendar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/aigrowth': typeof AppAigrowthRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/clube': typeof AppClubeRoute
  '/app/comandas': typeof AppComandasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/servicos': typeof AppServicosRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/aigrowth': typeof DemoAigrowthRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/profissionais': typeof DemoProfissionaisRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/servicos': typeof DemoServicosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaBarbearias': typeof MasterListaBarbeariasRoute
  '/master/novaBarbearia': typeof MasterNovaBarbeariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/aigrowth': typeof AppAigrowthRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/clube': typeof AppClubeRoute
  '/app/comandas': typeof AppComandasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/servicos': typeof AppServicosRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/aigrowth': typeof DemoAigrowthRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/profissionais': typeof DemoProfissionaisRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/servicos': typeof DemoServicosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaBarbearias': typeof MasterListaBarbeariasRoute
  '/master/novaBarbearia': typeof MasterNovaBarbeariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/master': typeof MasterRouteWithChildren
  '/reset-senha': typeof ResetSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/agendar/$slug': typeof AgendarSlugRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/aigrowth': typeof AppAigrowthRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/clube': typeof AppClubeRoute
  '/app/comandas': typeof AppComandasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/lembretes': typeof AppLembretesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/profissionais': typeof AppProfissionaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/servicos': typeof AppServicosRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/aigrowth': typeof DemoAigrowthRoute
  '/demo/clientes': typeof DemoClientesRoute
  '/demo/configuracoes': typeof DemoConfiguracoesRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/equipe': typeof DemoEquipeRoute
  '/demo/financeiro': typeof DemoFinanceiroRoute
  '/demo/profissionais': typeof DemoProfissionaisRoute
  '/demo/relatorios': typeof DemoRelatoriosRoute
  '/demo/servicos': typeof DemoServicosRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/listaBarbearias': typeof MasterListaBarbeariasRoute
  '/master/novaBarbearia': typeof MasterNovaBarbeariaRoute
  '/master/painel': typeof MasterPainelRoute
  '/master/planos': typeof MasterPlanosRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/agenda'
    | '/app/aigrowth'
    | '/app/checkout'
    | '/app/clientes'
    | '/app/clube'
    | '/app/comandas'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/lembretes'
    | '/app/onboarding'
    | '/app/produtos'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/servicos'
    | '/confirmar/$token'
    | '/demo/agenda'
    | '/demo/aigrowth'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/profissionais'
    | '/demo/relatorios'
    | '/demo/servicos'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/listaBarbearias'
    | '/master/novaBarbearia'
    | '/master/painel'
    | '/master/planos'
    | '/api/public/billing/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/agenda'
    | '/app/aigrowth'
    | '/app/checkout'
    | '/app/clientes'
    | '/app/clube'
    | '/app/comandas'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/lembretes'
    | '/app/onboarding'
    | '/app/produtos'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/servicos'
    | '/confirmar/$token'
    | '/demo/agenda'
    | '/demo/aigrowth'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/profissionais'
    | '/demo/relatorios'
    | '/demo/servicos'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/listaBarbearias'
    | '/master/novaBarbearia'
    | '/master/painel'
    | '/master/planos'
    | '/api/public/billing/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/entrar'
    | '/esqueci-senha'
    | '/master'
    | '/reset-senha'
    | '/trocar-senha'
    | '/agendar/$slug'
    | '/app/agenda'
    | '/app/aigrowth'
    | '/app/checkout'
    | '/app/clientes'
    | '/app/clube'
    | '/app/comandas'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/lembretes'
    | '/app/onboarding'
    | '/app/produtos'
    | '/app/profissionais'
    | '/app/relatorios'
    | '/app/servicos'
    | '/confirmar/$token'
    | '/demo/agenda'
    | '/demo/aigrowth'
    | '/demo/clientes'
    | '/demo/configuracoes'
    | '/demo/dashboard'
    | '/demo/equipe'
    | '/demo/financeiro'
    | '/demo/profissionais'
    | '/demo/relatorios'
    | '/demo/servicos'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/listaBarbearias'
    | '/master/novaBarbearia'
    | '/master/painel'
    | '/master/planos'
    | '/api/public/billing/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  MasterRoute: typeof MasterRouteWithChildren
  ResetSenhaRoute: typeof ResetSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  AgendarSlugRoute: typeof AgendarSlugRoute
  ConfirmarTokenRoute: typeof ConfirmarTokenRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/planos': {
      id: '/master/planos'
      path: '/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof MasterPlanosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/painel': {
      id: '/master/painel'
      path: '/painel'
      fullPath: '/master/painel'
      preLoaderRoute: typeof MasterPainelRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/novaBarbearia': {
      id: '/master/novaBarbearia'
      path: '/novaBarbearia'
      fullPath: '/master/novaBarbearia'
      preLoaderRoute: typeof MasterNovaBarbeariaRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/listaBarbearias': {
      id: '/master/listaBarbearias'
      path: '/listaBarbearias'
      fullPath: '/master/listaBarbearias'
      preLoaderRoute: typeof MasterListaBarbeariasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/assinaturas': {
      id: '/master/assinaturas'
      path: '/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/demo/servicos': {
      id: '/demo/servicos'
      path: '/servicos'
      fullPath: '/demo/servicos'
      preLoaderRoute: typeof DemoServicosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/relatorios': {
      id: '/demo/relatorios'
      path: '/relatorios'
      fullPath: '/demo/relatorios'
      preLoaderRoute: typeof DemoRelatoriosRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/profissionais': {
      id: '/demo/profissionais'
      path: '/profissionais'
      fullPath: '/demo/profissionais'
      preLoaderRoute: typeof DemoProfissionaisRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/financeiro': {
      id: '/demo/financeiro'
      path: '/financeiro'
      fullPath: '/demo/financeiro'
      preLoaderRoute: typeof DemoFinanceiroRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/equipe': {
      id: '/demo/equipe'
      path: '/equipe'
      fullPath: '/demo/equipe'
      preLoaderRoute: typeof DemoEquipeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/configuracoes': {
      id: '/demo/configuracoes'
      path: '/configuracoes'
      fullPath: '/demo/configuracoes'
      preLoaderRoute: typeof DemoConfiguracoesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/clientes': {
      id: '/demo/clientes'
      path: '/clientes'
      fullPath: '/demo/clientes'
      preLoaderRoute: typeof DemoClientesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/aigrowth': {
      id: '/demo/aigrowth'
      path: '/aigrowth'
      fullPath: '/demo/aigrowth'
      preLoaderRoute: typeof DemoAigrowthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agenda': {
      id: '/demo/agenda'
      path: '/agenda'
      fullPath: '/demo/agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/confirmar/$token': {
      id: '/confirmar/$token'
      path: '/confirmar/$token'
      fullPath: '/confirmar/$token'
      preLoaderRoute: typeof ConfirmarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profissionais': {
      id: '/app/profissionais'
      path: '/profissionais'
      fullPath: '/app/profissionais'
      preLoaderRoute: typeof AppProfissionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lembretes': {
      id: '/app/lembretes'
      path: '/lembretes'
      fullPath: '/app/lembretes'
      preLoaderRoute: typeof AppLembretesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comandas': {
      id: '/app/comandas'
      path: '/comandas'
      fullPath: '/app/comandas'
      preLoaderRoute: typeof AppComandasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clube': {
      id: '/app/clube'
      path: '/clube'
      fullPath: '/app/clube'
      preLoaderRoute: typeof AppClubeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aigrowth': {
      id: '/app/aigrowth'
      path: '/aigrowth'
      fullPath: '/app/aigrowth'
      preLoaderRoute: typeof AppAigrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/agendar/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAigrowthRoute: typeof AppAigrowthRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppClientesRoute: typeof AppClientesRoute
  AppClubeRoute: typeof AppClubeRoute
  AppComandasRoute: typeof AppComandasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppLembretesRoute: typeof AppLembretesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppProfissionaisRoute: typeof AppProfissionaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppServicosRoute: typeof AppServicosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAigrowthRoute: AppAigrowthRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppClientesRoute: AppClientesRoute,
  AppClubeRoute: AppClubeRoute,
  AppComandasRoute: AppComandasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppLembretesRoute: AppLembretesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppProfissionaisRoute: AppProfissionaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppServicosRoute: AppServicosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DemoRouteChildren {
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoAigrowthRoute: typeof DemoAigrowthRoute
  DemoClientesRoute: typeof DemoClientesRoute
  DemoConfiguracoesRoute: typeof DemoConfiguracoesRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoEquipeRoute: typeof DemoEquipeRoute
  DemoFinanceiroRoute: typeof DemoFinanceiroRoute
  DemoProfissionaisRoute: typeof DemoProfissionaisRoute
  DemoRelatoriosRoute: typeof DemoRelatoriosRoute
  DemoServicosRoute: typeof DemoServicosRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAgendaRoute: DemoAgendaRoute,
  DemoAigrowthRoute: DemoAigrowthRoute,
  DemoClientesRoute: DemoClientesRoute,
  DemoConfiguracoesRoute: DemoConfiguracoesRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoEquipeRoute: DemoEquipeRoute,
  DemoFinanceiroRoute: DemoFinanceiroRoute,
  DemoProfissionaisRoute: DemoProfissionaisRoute,
  DemoRelatoriosRoute: DemoRelatoriosRoute,
  DemoServicosRoute: DemoServicosRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface MasterRouteChildren {
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterListaBarbeariasRoute: typeof MasterListaBarbeariasRoute
  MasterNovaBarbeariaRoute: typeof MasterNovaBarbeariaRoute
  MasterPainelRoute: typeof MasterPainelRoute
  MasterPlanosRoute: typeof MasterPlanosRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterListaBarbeariasRoute: MasterListaBarbeariasRoute,
  MasterNovaBarbeariaRoute: MasterNovaBarbeariaRoute,
  MasterPainelRoute: MasterPainelRoute,
  MasterPlanosRoute: MasterPlanosRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  MasterRoute: MasterRouteWithChildren,
  ResetSenhaRoute: ResetSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  AgendarSlugRoute: AgendarSlugRoute,
  ConfirmarTokenRoute: ConfirmarTokenRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
